/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TinTucRouteImport } from './routes/tin-tuc'
import { Route as OnThiRouteImport } from './routes/on-thi'
import { Route as CheckQuyHoachRouteImport } from './routes/check-quy-hoach'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoiGioiIndexRouteImport } from './routes/moi-gioi.index'
import { Route as DuAnIndexRouteImport } from './routes/du-an.index'
import { Route as MoiGioiSlugRouteImport } from './routes/moi-gioi.$slug'
import { Route as DuAnSlugRouteImport } from './routes/du-an.$slug'

const TinTucRoute = TinTucRouteImport.update({
  id: '/tin-tuc',
  path: '/tin-tuc',
  getParentRoute: () => rootRouteImport,
} as any)
const OnThiRoute = OnThiRouteImport.update({
  id: '/on-thi',
  path: '/on-thi',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckQuyHoachRoute = CheckQuyHoachRouteImport.update({
  id: '/check-quy-hoach',
  path: '/check-quy-hoach',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoiGioiIndexRoute = MoiGioiIndexRouteImport.update({
  id: '/moi-gioi/',
  path: '/moi-gioi/',
  getParentRoute: () => rootRouteImport,
} as any)
const DuAnIndexRoute = DuAnIndexRouteImport.update({
  id: '/du-an/',
  path: '/du-an/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoiGioiSlugRoute = MoiGioiSlugRouteImport.update({
  id: '/moi-gioi/$slug',
  path: '/moi-gioi/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DuAnSlugRoute = DuAnSlugRouteImport.update({
  id: '/du-an/$slug',
  path: '/du-an/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/check-quy-hoach': typeof CheckQuyHoachRoute
  '/on-thi': typeof OnThiRoute
  '/tin-tuc': typeof TinTucRoute
  '/du-an/$slug': typeof DuAnSlugRoute
  '/moi-gioi/$slug': typeof MoiGioiSlugRoute
  '/du-an/': typeof DuAnIndexRoute
  '/moi-gioi/': typeof MoiGioiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/check-quy-hoach': typeof CheckQuyHoachRoute
  '/on-thi': typeof OnThiRoute
  '/tin-tuc': typeof TinTucRoute
  '/du-an/$slug': typeof DuAnSlugRoute
  '/moi-gioi/$slug': typeof MoiGioiSlugRoute
  '/du-an': typeof DuAnIndexRoute
  '/moi-gioi': typeof MoiGioiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/check-quy-hoach': typeof CheckQuyHoachRoute
  '/on-thi': typeof OnThiRoute
  '/tin-tuc': typeof TinTucRoute
  '/du-an/$slug': typeof DuAnSlugRoute
  '/moi-gioi/$slug': typeof MoiGioiSlugRoute
  '/du-an/': typeof DuAnIndexRoute
  '/moi-gioi/': typeof MoiGioiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/check-quy-hoach'
    | '/on-thi'
    | '/tin-tuc'
    | '/du-an/$slug'
    | '/moi-gioi/$slug'
    | '/du-an/'
    | '/moi-gioi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/check-quy-hoach'
    | '/on-thi'
    | '/tin-tuc'
    | '/du-an/$slug'
    | '/moi-gioi/$slug'
    | '/du-an'
    | '/moi-gioi'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/check-quy-hoach'
    | '/on-thi'
    | '/tin-tuc'
    | '/du-an/$slug'
    | '/moi-gioi/$slug'
    | '/du-an/'
    | '/moi-gioi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CheckQuyHoachRoute: typeof CheckQuyHoachRoute
  OnThiRoute: typeof OnThiRoute
  TinTucRoute: typeof TinTucRoute
  DuAnSlugRoute: typeof DuAnSlugRoute
  MoiGioiSlugRoute: typeof MoiGioiSlugRoute
  DuAnIndexRoute: typeof DuAnIndexRoute
  MoiGioiIndexRoute: typeof MoiGioiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tin-tuc': {
      id: '/tin-tuc'
      path: '/tin-tuc'
      fullPath: '/tin-tuc'
      preLoaderRoute: typeof TinTucRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/on-thi': {
      id: '/on-thi'
      path: '/on-thi'
      fullPath: '/on-thi'
      preLoaderRoute: typeof OnThiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-quy-hoach': {
      id: '/check-quy-hoach'
      path: '/check-quy-hoach'
      fullPath: '/check-quy-hoach'
      preLoaderRoute: typeof CheckQuyHoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moi-gioi/': {
      id: '/moi-gioi/'
      path: '/moi-gioi'
      fullPath: '/moi-gioi/'
      preLoaderRoute: typeof MoiGioiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/du-an/': {
      id: '/du-an/'
      path: '/du-an'
      fullPath: '/du-an/'
      preLoaderRoute: typeof DuAnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moi-gioi/$slug': {
      id: '/moi-gioi/$slug'
      path: '/moi-gioi/$slug'
      fullPath: '/moi-gioi/$slug'
      preLoaderRoute: typeof MoiGioiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/du-an/$slug': {
      id: '/du-an/$slug'
      path: '/du-an/$slug'
      fullPath: '/du-an/$slug'
      preLoaderRoute: typeof DuAnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CheckQuyHoachRoute: CheckQuyHoachRoute,
  OnThiRoute: OnThiRoute,
  TinTucRoute: TinTucRoute,
  DuAnSlugRoute: DuAnSlugRoute,
  MoiGioiSlugRoute: MoiGioiSlugRoute,
  DuAnIndexRoute: DuAnIndexRoute,
  MoiGioiIndexRoute: MoiGioiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
