/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnThiRouteImport } from './routes/on-thi'
import { Route as NhaDatChoThueRouteImport } from './routes/nha-dat-cho-thue'
import { Route as NhaDatBanRouteImport } from './routes/nha-dat-ban'
import { Route as CheckQuyHoachRouteImport } from './routes/check-quy-hoach'
import { Route as BanDatRouteImport } from './routes/ban-dat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TinTucIndexRouteImport } from './routes/tin-tuc.index'
import { Route as MoiGioiIndexRouteImport } from './routes/moi-gioi.index'
import { Route as DuAnIndexRouteImport } from './routes/du-an.index'
import { Route as TinTucSlugRouteImport } from './routes/tin-tuc.$slug'
import { Route as MoiGioiSlugRouteImport } from './routes/moi-gioi.$slug'
import { Route as DuAnSlugRouteImport } from './routes/du-an.$slug'

const OnThiRoute = OnThiRouteImport.update({
  id: '/on-thi',
  path: '/on-thi',
  getParentRoute: () => rootRouteImport,
} as any)
const NhaDatChoThueRoute = NhaDatChoThueRouteImport.update({
  id: '/nha-dat-cho-thue',
  path: '/nha-dat-cho-thue',
  getParentRoute: () => rootRouteImport,
} as any)
const NhaDatBanRoute = NhaDatBanRouteImport.update({
  id: '/nha-dat-ban',
  path: '/nha-dat-ban',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckQuyHoachRoute = CheckQuyHoachRouteImport.update({
  id: '/check-quy-hoach',
  path: '/check-quy-hoach',
  getParentRoute: () => rootRouteImport,
} as any)
const BanDatRoute = BanDatRouteImport.update({
  id: '/ban-dat',
  path: '/ban-dat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TinTucIndexRoute = TinTucIndexRouteImport.update({
  id: '/tin-tuc/',
  path: '/tin-tuc/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoiGioiIndexRoute = MoiGioiIndexRouteImport.update({
  id: '/moi-gioi/',
  path: '/moi-gioi/',
  getParentRoute: () => rootRouteImport,
} as any)
const DuAnIndexRoute = DuAnIndexRouteImport.update({
  id: '/du-an/',
  path: '/du-an/',
  getParentRoute: () => rootRouteImport,
} as any)
const TinTucSlugRoute = TinTucSlugRouteImport.update({
  id: '/tin-tuc/$slug',
  path: '/tin-tuc/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MoiGioiSlugRoute = MoiGioiSlugRouteImport.update({
  id: '/moi-gioi/$slug',
  path: '/moi-gioi/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DuAnSlugRoute = DuAnSlugRouteImport.update({
  id: '/du-an/$slug',
  path: '/du-an/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/ban-dat': typeof BanDatRoute
  '/check-quy-hoach': typeof CheckQuyHoachRoute
  '/nha-dat-ban': typeof NhaDatBanRoute
  '/nha-dat-cho-thue': typeof NhaDatChoThueRoute
  '/on-thi': typeof OnThiRoute
  '/du-an/$slug': typeof DuAnSlugRoute
  '/moi-gioi/$slug': typeof MoiGioiSlugRoute
  '/tin-tuc/$slug': typeof TinTucSlugRoute
  '/du-an/': typeof DuAnIndexRoute
  '/moi-gioi/': typeof MoiGioiIndexRoute
  '/tin-tuc/': typeof TinTucIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/ban-dat': typeof BanDatRoute
  '/check-quy-hoach': typeof CheckQuyHoachRoute
  '/nha-dat-ban': typeof NhaDatBanRoute
  '/nha-dat-cho-thue': typeof NhaDatChoThueRoute
  '/on-thi': typeof OnThiRoute
  '/du-an/$slug': typeof DuAnSlugRoute
  '/moi-gioi/$slug': typeof MoiGioiSlugRoute
  '/tin-tuc/$slug': typeof TinTucSlugRoute
  '/du-an': typeof DuAnIndexRoute
  '/moi-gioi': typeof MoiGioiIndexRoute
  '/tin-tuc': typeof TinTucIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/ban-dat': typeof BanDatRoute
  '/check-quy-hoach': typeof CheckQuyHoachRoute
  '/nha-dat-ban': typeof NhaDatBanRoute
  '/nha-dat-cho-thue': typeof NhaDatChoThueRoute
  '/on-thi': typeof OnThiRoute
  '/du-an/$slug': typeof DuAnSlugRoute
  '/moi-gioi/$slug': typeof MoiGioiSlugRoute
  '/tin-tuc/$slug': typeof TinTucSlugRoute
  '/du-an/': typeof DuAnIndexRoute
  '/moi-gioi/': typeof MoiGioiIndexRoute
  '/tin-tuc/': typeof TinTucIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/ban-dat'
    | '/check-quy-hoach'
    | '/nha-dat-ban'
    | '/nha-dat-cho-thue'
    | '/on-thi'
    | '/du-an/$slug'
    | '/moi-gioi/$slug'
    | '/tin-tuc/$slug'
    | '/du-an/'
    | '/moi-gioi/'
    | '/tin-tuc/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/ban-dat'
    | '/check-quy-hoach'
    | '/nha-dat-ban'
    | '/nha-dat-cho-thue'
    | '/on-thi'
    | '/du-an/$slug'
    | '/moi-gioi/$slug'
    | '/tin-tuc/$slug'
    | '/du-an'
    | '/moi-gioi'
    | '/tin-tuc'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/ban-dat'
    | '/check-quy-hoach'
    | '/nha-dat-ban'
    | '/nha-dat-cho-thue'
    | '/on-thi'
    | '/du-an/$slug'
    | '/moi-gioi/$slug'
    | '/tin-tuc/$slug'
    | '/du-an/'
    | '/moi-gioi/'
    | '/tin-tuc/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BanDatRoute: typeof BanDatRoute
  CheckQuyHoachRoute: typeof CheckQuyHoachRoute
  NhaDatBanRoute: typeof NhaDatBanRoute
  NhaDatChoThueRoute: typeof NhaDatChoThueRoute
  OnThiRoute: typeof OnThiRoute
  DuAnSlugRoute: typeof DuAnSlugRoute
  MoiGioiSlugRoute: typeof MoiGioiSlugRoute
  TinTucSlugRoute: typeof TinTucSlugRoute
  DuAnIndexRoute: typeof DuAnIndexRoute
  MoiGioiIndexRoute: typeof MoiGioiIndexRoute
  TinTucIndexRoute: typeof TinTucIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/on-thi': {
      id: '/on-thi'
      path: '/on-thi'
      fullPath: '/on-thi'
      preLoaderRoute: typeof OnThiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nha-dat-cho-thue': {
      id: '/nha-dat-cho-thue'
      path: '/nha-dat-cho-thue'
      fullPath: '/nha-dat-cho-thue'
      preLoaderRoute: typeof NhaDatChoThueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nha-dat-ban': {
      id: '/nha-dat-ban'
      path: '/nha-dat-ban'
      fullPath: '/nha-dat-ban'
      preLoaderRoute: typeof NhaDatBanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-quy-hoach': {
      id: '/check-quy-hoach'
      path: '/check-quy-hoach'
      fullPath: '/check-quy-hoach'
      preLoaderRoute: typeof CheckQuyHoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ban-dat': {
      id: '/ban-dat'
      path: '/ban-dat'
      fullPath: '/ban-dat'
      preLoaderRoute: typeof BanDatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tin-tuc/': {
      id: '/tin-tuc/'
      path: '/tin-tuc'
      fullPath: '/tin-tuc/'
      preLoaderRoute: typeof TinTucIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moi-gioi/': {
      id: '/moi-gioi/'
      path: '/moi-gioi'
      fullPath: '/moi-gioi/'
      preLoaderRoute: typeof MoiGioiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/du-an/': {
      id: '/du-an/'
      path: '/du-an'
      fullPath: '/du-an/'
      preLoaderRoute: typeof DuAnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tin-tuc/$slug': {
      id: '/tin-tuc/$slug'
      path: '/tin-tuc/$slug'
      fullPath: '/tin-tuc/$slug'
      preLoaderRoute: typeof TinTucSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moi-gioi/$slug': {
      id: '/moi-gioi/$slug'
      path: '/moi-gioi/$slug'
      fullPath: '/moi-gioi/$slug'
      preLoaderRoute: typeof MoiGioiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/du-an/$slug': {
      id: '/du-an/$slug'
      path: '/du-an/$slug'
      fullPath: '/du-an/$slug'
      preLoaderRoute: typeof DuAnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BanDatRoute: BanDatRoute,
  CheckQuyHoachRoute: CheckQuyHoachRoute,
  NhaDatBanRoute: NhaDatBanRoute,
  NhaDatChoThueRoute: NhaDatChoThueRoute,
  OnThiRoute: OnThiRoute,
  DuAnSlugRoute: DuAnSlugRoute,
  MoiGioiSlugRoute: MoiGioiSlugRoute,
  TinTucSlugRoute: TinTucSlugRoute,
  DuAnIndexRoute: DuAnIndexRoute,
  MoiGioiIndexRoute: MoiGioiIndexRoute,
  TinTucIndexRoute: TinTucIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
